93 함께전시 모집글 조회 기능
Museum-Mate/museum-mate-be pull request #107
Opened 2023-01-31 12:10 UTC by leejoonsang

## :information_desk_person: 간단 소개
함께전시 모집글 전체/상세 조회 기능 구현

## :heavy_check_mark: 작업 내용 설명
- GatheringController, GatheringService, 그리고 Gathering 관련 데이터 리팩토링을 포함해 함께전시 모집글을 조회할 수 있는 기능 구현
- 모집글 전체/상세 조회 기능에 대한 테스트코드 작성(성공, 실패)

## :bulb: 참고사항
확인 부탁드립니다!

2023-02-02 06:08 UTC, Geuun requested changes

2023-02-02 06:08 UTC, geuun commented on src/main/java/com/dev/museummate/service/GatheringService.java
> +    public Page<GatheringDto> findAllGatherings(Pageable pageable) {
다른 도메인 Service Layer과 동일하게

DTO 클래스로 반환하게 리펙토링 부탁드립니다 :)

2023-02-02 06:08 UTC, geuun commented on src/main/java/com/dev/museummate/domain/dto/gathering/GatheringDto.java
> +
DTO에는 Entity랑 역활 분리를 위한 클래스라서
컬럼 관계 안맺어주셔도 됩니다!

따라서 어노테이션들 지워주시면 될 것  같습니다!

2023-02-02 06:08 UTC, Geuun commented on src/main/java/com/dev/museummate/controller/GatheringController.java
> +                                                 .createdAt(gatheringResponse.getCreatedAt())
Controller Layer에서 Service Layer로부터 

DTO 타입으로 받아서 Response로 반환하게 수정 부탁드립니다!

2023-02-02 06:08 UTC, Geuun commented on src/main/java/com/dev/museummate/controller/GatheringController.java
> -        Page<GatheringDto> gatheringDtos = gatheringService.findAllGatherings(pageable);
다른 도메인도 이렇게 반환하고 있어서

수정 전처럼 반환해주시면 되요..!

2023-02-02 09:40 UTC, chlalswns200 commented
말씀해주신 사항 다 반영하고 테스트 까지 완료 했습니다.
다시 확인 부탁드립니다

2023-02-03 05:16 UTC, Geuun approved these changes
병합시 일어났던 Complict 를 해결했습니다..!

리펙토링하시느랴 고생하셨습니다!

바로 병합 진행하겠습니다!

2023-02-03 05:16 UTC, merged